#ifndef NODE_H_
#define NODE_H_

#include <mutex>
#include <queue>

#include "message.h"

struct Node {
  // Structure information and data buffer for each tree.
  std::vector<int> p;                  // Parent node id in the tree.
  std::vector<int> level;              // Level in the tree, root is 0.  Only used for hubs.
  std::priority_queue<Message> q;  // Incoming event queue for this node.
  std::vector< std::deque<Message> > buf;// Local state, used for aggregation.

  int64_t in, out;        // In/outbound traffic during current time slice.
  int64_t in_limit, out_limit;    // BW limit for each time slice.
  int64_t in_per_sec, out_per_sec;  // Total in/outbound traffic aggregated by seconds.
  int64_t self_per_sec;       // Total bytes of messages generated by itself.
  int64_t eff_out_per_sec;    // Effective outbound traffic in a second.

  int64_t msgs_per_tick;  // #msgs generated by this node per tick.

  std::vector<bool> gc;      // Is GC enabled?
  std::vector<int> gc_delay; // Dalay caused by GC in ms, only effective when gc is on.


  int64_t total_in_msgs, total_out_msgs;  // Bookkeeping #msgs received/sent.
  int64_t saved_per_sec; // Bookkeeping #msgs saved due to aggregation.
};


#endif // NODE_H_
