#ifndef NODE_H_
#define NODE_H_

#include <mutex>
#include <queue>

#include "message.h"

struct Node {
  int p;                  // Parent node id in the tree.
  std::queue<Message> q;  // Incoming event queue for this node.
  std::deque<Message> buf;// Local state, used for aggregation.

  int64_t in, out;        // In/outbound traffic during current time slice.
  int64_t in_limit, out_limit;    // BW limit for each time slice.
  int64_t in_per_sec, out_per_sec;  // Total in/outbound traffic aggregated by seconds.

  int64_t msgs_per_tick;  // #msgs generated by this node per tick.

  bool gc;

  int64_t total_in_msgs, total_out_msgs;  // Bookkeeping #msgs received/sent.
  int64_t total_self_msgs;    // Bookkeeping total #msgs generated by itself.
  int64_t msgs_saved;     // Bookkeeping #msgs saved due to aggregation.
};


#endif // NODE_H_
